# Generated by Django 5.2.7 on 2025-10-04 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('farm_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farming_type', models.CharField(choices=[('crop', 'Crop Farming'), ('livestock', 'Livestock Farming'), ('mixed', 'Mixed Farming')], max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AidApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources_needed', models.CharField(choices=[('seedlings', 'Seedlings'), ('fertilizers', 'Fertilizers'), ('pesticides', 'Pesticides'), ('livestock_vaccines', 'Livestock Vaccines'), ('equipment', 'Farming Equipment'), ('financial_support', 'Financial Support')], max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.farmer')),
            ],
            options={
                'unique_together': {('farmer', 'resources_needed')},
            },
        ),
    ]
