# Generated by Django 5.2.7 on 2025-10-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_farmer_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aidapplication',
            unique_together=set(),
        ),
    ]
