# Generated by Django 5.2.7 on 2025-11-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_created_at_notification_date_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('single', 'Single Farmer'), ('all', 'All Farmers')], default='single', max_length=10),
        ),
    ]
