# Generated by Django 5.2.7 on 2025-10-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farming_type',
            field=models.CharField(blank=True, choices=[('crop', 'Crop Farming'), ('livestock', 'Livestock Farming'), ('mixed', 'Mixed Farming')], max_length=50, null=True),
        ),
    ]
