# Generated by Django 5.2.7 on 2025-11-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notification_recipient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
