# Generated by Django 5.2.7 on 2025-11-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmessage_replied_at_contactmessage_replied_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_reply_seen',
            field=models.BooleanField(default=False),
        ),
    ]
