# Generated by Django 5.2.7 on 2025-11-06 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactmessage_is_reply_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('seedlings', 'Seedlings'), ('fertilizers', 'Fertilizers'), ('pesticides', 'Pesticides'), ('livestock_vaccines', 'Livestock Vaccines'), ('equipment', 'Farming Equipment'), ('financial_support', 'Financial Support')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('application_start', models.DateField()),
                ('application_deadline', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='aidapplication',
            name='aid_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aiditem'),
        ),
    ]
