# Generated by Django 5.2.7 on 2025-11-06 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aiditem_aidapplication_aid_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiditem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aiditem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='aiditem',
            name='is_open_for_application',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aiditem',
            name='name',
            field=models.CharField(choices=[('fertilizer', 'Fertilizer'), ('seedlings', 'Seedlings'), ('pesticides', 'Pesticides'), ('animal_feed', 'Animal Feed'), ('other', 'Other')], max_length=100),
        ),
        migrations.CreateModel(
            name='SubAidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('aid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='core.aiditem')),
            ],
        ),
    ]
