# Generated by Django 5.2.7 on 2025-11-07 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_aiditem_description_remove_aiditem_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidapplication',
            name='resources_needed',
        ),
        migrations.AddField(
            model_name='aidapplication',
            name='sub_aid_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subaiditem'),
        ),
    ]
