# Generated by Django 5.2.7 on 2025-11-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_aidapplication_resources_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiditem',
            name='subitems',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
