# Generated by Django 5.2.7 on 2025-11-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aiditem_subitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidapplication',
            name='quantity_requested',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
