# Generated by Django 5.2.7 on 2025-11-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aidapplication_quantity_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidapplication',
            name='quantity_requested',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
